version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 559672757114.dkr.ecr.eu-west-3.amazonaws.com
      - REPOSITORY_URI=559672757114.dkr.ecr.eu-west-3.amazonaws.com/vso-user-backend
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Image pushed: $REPOSITORY_URI:$IMAGE_TAG"
artifacts:
  files:
    - '**/*'
